// com.finops.finopsbk.dto.TransactionRequest.java
package com.finops.finopsbk.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID; // For accountId

// This DTO directly matches the incoming JSON payload structure
public class TransactionRequest {
    // No txn_id here, as it's generated by DB
    private UUID accountId; // Changed from Account object to just its ID
    private BigDecimal amount;
    private String method;
    private LocalDateTime timestamp;
    private String location;
    private String deviceId;
    private String status;
    private Boolean isFraud = false; // Initial default
    private Boolean isFlagged = false; // Initial default

    // Getters and Setters for all fields
    public UUID getAccountId() { return accountId; }
    public void setAccountId(UUID accountId) { this.accountId = accountId; }
    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }
    public String getMethod() { return method; }
    public void setMethod(String method) { this.method = method; }
    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public String getDeviceId() { return deviceId; }
    public void setDeviceId(String deviceId) { this.deviceId = deviceId; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public Boolean getIsFraud() { return isFraud; }
    public void setIsFraud(Boolean isFraud) { this.isFraud = isFraud; }
    public Boolean getIsFlagged() { return isFlagged; }
    public void setIsFlagged(Boolean isFlagged) { this.isFlagged = isFlagged; }
}